name: holomobilecoding
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  dio: ^5.3.4
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  cached_network_image: ^3.3.0
  json_annotation: ^4.8.1
  go_router: ^12.1.3
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true